# ~/dotfiles/config/alacritty/alacritty.toml

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 } # 少し余白を開けるとオシャレ
dynamic_padding = true
opacity = 0.95               # ほんの少し透過させる（お好みで 1.0 に）

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"
