---
- name: 変数の定義
  ansible.builtin.set_fact:
    nvm_version: "v0.40.3"
    node_version: "24"
    nvm_dir: "{{ ansible_user_dir }}/.nvm"

- name: 必要なパッケージのインストール (curl)
  ansible.builtin.apt:
    name: curl
    state: present
  become: true

- name: nvmのインストール
  ansible.builtin.shell: |
    set -o pipefail
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
  args:
    executable: /bin/bash
    creates: "{{ nvm_dir }}/nvm.sh"

- name: Node.js (v{{ node_version }}) のインストール
  ansible.builtin.shell: |
    . {{ nvm_dir }}/nvm.sh
    nvm install {{ node_version }}
  args:
    executable: /bin/bash
    # 指定バージョンのnode実行ファイルがあればスキップ（冪等性担保）
    creates: "{{ nvm_dir }}/versions/node/v{{ node_version }}*/bin/node"

- name: デフォルトバージョンの設定 (alias default)
  ansible.builtin.shell: |
    . {{ nvm_dir }}/nvm.sh
    nvm alias default {{ node_version }}
  args:
    executable: /bin/bash
  changed_when: false

# Docker Install
- name: Install required packages for Docker
  become: true
  apt:
    name:
      - ca-certificates
      - curl
    state: present
    # local.yml ですでに update_cache しているため以下は不要
    # update_cache: yes

- name: Create /etc/apt/keyrings directory
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  become: true
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

# NOTE: deb822_repository モジュールを使うほうが良いが、バージョンが古いと使えない
# よって、現時点では手動で sources.list ファイルを作成する方法を採用
- name: Add Docker apt repository
  become: true
  copy:
    dest: /etc/apt/sources.list.d/docker.sources
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: {{ ansible_distribution_release }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc
  
- name: Install Docker Engine
  become: true
  apt:
    name:
      - docker-ce 
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

# Pip, venv Install
- name: Install pip and venv
  become: true
  apt:
    name:
      - python3-pip
      - python3-venv
    state: present