add_newline = false

format = """
[](fg:#303030)\
$username\
[](fg:#0087AF bg:#303030)\
$directory\
[](fg:#303030 bg:#D7005F)\
$git_branch$git_status\
[](fg:#D7005F bg:#0087AF)\
$docker_context\
[](fg:#0087AF bg:#303030)\
$time\
[](fg:#303030)\
$line_break$character
"""

[username]
show_always = true
format = "[   $user ]($style)"
style_user = "bg:#0087AF fg:#ffffff"

[directory]
format = "[   $path ]($style)"
style = "bg:#303030 fg:#ffffff"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = " "
format = "[ $symbol$branch ]($style)"
style = "bg:#D7005F fg:#ffffff"

[git_status]
style = "bg:#D7005F fg:#ffffff"
format = "[[($all_status$ahead_behind )](fg:#ffffff bg:#D7005F)]($style)"

[docker_context]
symbol = " "
style = "bg:#D7005F fg:#ffffff"
format = "[](fg:#D7005F bg:#D7005F)[$symbol $context]($style)"

[time]
disabled = false
format = "[  $time ]($style)"
time_format = "%H:%M"
style = "bg:#303030 fg:#ffffff"

[character]
success_symbol = "[❯](bold #0087AF) "
error_symbol   = "[❯](bold #D7005F) "