---
# VS Code を apt でインストールする Role

- name: Ensure required packages are installed
  become: true
  apt:
    name:
      - wget
      - gpg
    state: present
    update_cache: yes

- name: Add Microsoft GPG key
  become: true
  ansible.builtin.shell: |
    wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /usr/share/keyrings/microsoft.gpg > /dev/null
  args:
    executable: /bin/bash
  changed_when: false
  tags: vscode

- name: Add VS Code apt repository
  become: true
  copy:
    dest: /etc/apt/sources.list.d/vscode.list
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/code stable main
  notify:
    - apt update
  tags: vscode

- name: Install VS Code
  become: true
  apt:
    name: code
    state: latest
  tags: vscode
